### ISSUE TITLE
GameManager

### ISSUE THREAD

**Issue by 13alazs** [13alazs/Project-Protectors#10]
Ez az osztály felelős a játékmenet kezeléséért. A harc körökre osztott, az ellenfelek és a játékos karakterei mind bekerülnek egy sorba az initiative értékük alapján, mely meghatározza melyik karakter melyik után jön, ám képességek hatására a játék során módosulhat ez a sorrend. A csatatér 5-5 hellyel rendelkezik a játékos karakterei és az ellenfelek számára, ám ezek közül nem feltétlen van mindig mindegyik kihasználva (meghalt egy karakter, vagy kevesebb ellenfél van az adott pályán).

**Comment by FodorAdam** [comment]
Úgy érzem, ez egy elég nagy méretű kódrészlet lenne magában, ezért a teljes kóddal semmiképpen sem tudok végezni a CI határidejéig, de esetleg egy működőképes, félkész kódot feltehetek, ha kellene
