### ISSUE TITLE
Tesztelés

### ISSUE THREAD

**Issue by FodorAdam** [13alazs/Project-Protectors#19]
Egyetlen paranccsal futtatható, JUnit-os, nem kamu tesztek kellenek.

**Comment by 13alazs** [comment]
Fontos, hogy a teszteket automatikusan futassa a mavennel implementált script és ezáltal a CI rendszer is. A teszteket el lehet kezdeni már írni, azonban merge előtt mindenképpen tesztelni kell, miután az alábbi jegyek bementek:
[Tesztelés #19](https://github.com/FodorAdam/Project-Protectors/issues/18)
[Hotfix - hiányzó dependenciák #20](https://github.com/FodorAdam/Project-Protectors/issues/20)
