### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by FodorAdam** [13alazs/Project-Protectors#33]
The UI is functional, but it looks bad, we need to improve, we need sprites, maybe a logo for the game, this kind of thing.

**Comment by 13alazs** [comment]
I started to improve the main menu. I'm also planning to add a logo for the game and placeholder images waiting for later improvements.

**Comment by 13alazs** [comment]
A linkelt pr tartalmazza a menu és submenu-k újradesign-olását, új hátteret, javított user experience-t. Az ingame UI még nem követi ezt a design-t, az később lesz javítva.
[Ingame UI #57](https://github.com/13alazs/Project-Protectors/issues/57)
