### ISSUE TITLE
Javadoc

### ISSUE THREAD

**Issue by FodorAdam** [13alazs/Project-Protectors#34]
Az egyik 3. beadandóra tervezett extra eszköz a javadoc. Ennek implementációját kell megvalósítani a maven segítségével.

Note from Ádám:
A másik csoportmunkában az ANT build.xml-ébe tettem a javadoc generálását, gondolom itt a mavenbe kell rakni.

**Comment by 13alazs** [comment]
Javaslom, hogy a generált dokumentációt közösen is nézzük át a tervezett belső demo során.
