### ISSUE TITLE
Lint tool implementálása

### ISSUE THREAD

**Issue by 13alazs** [13alazs/Project-Protectors#38]
A megbeszéltek szerint a 3. beadandóra szánt egyik eszköz egy linting tool, ami elősegíti a kódminőség javulását és a későbbiekben is a kód tisztán tartását.

**Comment by DoraZasz** [comment]
Végül nem egészen egy linting tool lett, hanem egy codeformatter, ami szükség esetén kijelzi az elvárttól eltérően formázott kódrészeket, és azokat automatikusan átformázza a fordítás során.
