### ISSUE TITLE
Repository kitakarítása és rendszerezése a megadottak szerint

### ISSUE THREAD

**Issue by 13alazs** [13alazs/Project-Protectors#4]
Lásd táblázat és fölötte leírtak:
[1.Beadandó leírás](https://canvas.elte.hu/courses/15366/assignments/102274)
[2.Beadandó leírás](https://canvas.elte.hu/courses/15366/assignments/102270)

Fontos: minden IDE-val (NetBeans) kapcsolatos függőséget ki kell írtani a repository-ból (lásd README)

**Comment by FodorAdam** [comment]
Egy fontos változtatás, kedd este átadtam a repót Balázsnak, így a repó elérési útvonalát is meg kell változtatni a README.md-ben.
