### ISSUE TITLE
[EPIC] Feedback

### ISSUE THREAD

**Issue by FodorAdam** [13alazs/Project-Protectors#42]
Persze lehet csak console-ra kiírogatni adatokat, van is egy algoritmusom adatok console-ra való kiírására, esetleg beletehetem, de nem túl intuitív, ezért lehetne a karakterek dolgait (hp, resource) kiírni itt-ott (karakter felett, képesség gombok mellett)

**Comment by 13alazs** [comment]
Ezt szétbontom részfeladatokra, @DoraZasz ha jól tudom ezzel már foglalkoztál, úgyhogy kérlek vedd magadra amikbe már belekezdtél.

[Egyszerű animációk #41](https://github.com/13alazs/Project-Protectors/issues/41)
[Console logok és felesleges kommentek kitakarítása #62](https://github.com/13alazs/Project-Protectors/issues/62)
[Sebzés és heal indikátorok #63](https://github.com/13alazs/Project-Protectors/issues/63)
